PIN_RADIUS_LARGE = 6.6/2
PIN_RADIUS_SMALL = 6/2
PIN_LENGTH = 26
PIN_DISTANCE_VERTICAL = 32
PIN_DISTANCE_HORIZONTAL = 26

STAND_WIDTH = 44
STAND_DEPTH = 32.5

STAND_CHAMFER = 1.5

STAND_RUNG_WIDTH = 11
STAND_RUNG_HEIGHT = 42

STAND_DESK_GAP = 3

STAND_PIN_HOLE_TO_EDGE = (STAND_WIDTH - PIN_DISTANCE_HORIZONTAL) / 2

SHELF_HEIGHT = 18
SHELF_PIERCING_TO_SURFACE = 12
