[tool.poetry]
name = 'solid-printer-model'
version = '0'
description = ''
authors = ['Petr Tuma <ceres@tmatmouci.cz>']

[tool.poetry.dependencies]
python = '^3.9'
solidpython = '^1.1'

[tool.poetry.dev-dependencies]

[build-system]
requires = ['poetry >= 1.0']
build-backend = 'poetry.masonry.api'
